GET http://localhost:5082/games

###
GET http://localhost:5082/games/5AEFF6C8-9828-4D03-90F6-F809CFBF7680

###
POST http://localhost:5082/games
Content-Type: application/json

{
    "name": "TEST GAME",
    "genreId": "C0FE34BF-1E5F-43A0-B370-AB7C45B388C1",
    "price": 19.99,
    "releaseDate": "1992-07-15",
    "description": "Test Description"
}

###
PUT http://localhost:5082/games/5AEFF6C8-9828-4D03-90F6-F809CFBF7680
Content-Type: application/json

{
    "name": "Minecraft for Windows",
    "genreId": "AF333D56-2146-4899-9ABE-BA9ABD7EFC83",
    "price": 7.97,
    "releaseDate": "2011-11-18",
    "description": "Survive the night or create a work of art in the hit sandbox game! Build anything you can imagine, uncover mysteries, and face thrilling foes in an infinite world that's unique in every playthrough. There's no wrong way to play!"
}

###
DELETE http://localhost:5082/games/a0eaa60b-058c-4ec4-9412-2c0913725b06

###
GET http://localhost:5082/genres